[package]
name = "windmill-parser-ts"
version = "1.41.0"
authors = ["Ruben Fiszel <ruben@windmill.dev>"]
edition = "2021"

[lib]
name = "windmill_parser_ts"
path = "./src/lib.rs"

[dependencies]
windmill-parser.workspace = true
windmill-common.workspace = true
deno_core.workspace = true
swc_common.workspace = true
swc_ecma_parser.workspace = true
swc_ecma_ast.workspace = true
serde_json.workspace = true
anyhow.workspace = true
