[package]
name = "windmill-parser-go"
version = "1.41.0"
authors = ["Ruben Fiszel <ruben@windmill.dev>"]
edition = "2021"

[lib]
name = "windmill_parser_go"
path = "./src/lib.rs"

[dependencies]
windmill-parser.workspace = true
windmill-common.workspace = true
phf.workspace = true
unicode-general-category.workspace = true
itertools.workspace = true
anyhow.workspace = true
