[build]
rustflags = ["--cfg", "tokio_unstable", "-C", "link-arg=-fuse-ld=lld"]
incremental = true

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]
