[package]
name = "windmill-worker"
version.workspace = true
authors.workspace = true
edition.workspace = true
default-run = "worker"

[[bin]]
name = "worker"
path = "./src/main.rs"

[features]
default = ["deno", "go"]
deno = [
    "dep:deno_core",
    "dep:swc_common",
    "dep:swc_ecma_parser",
    "dep:swc_ecma_ast",
]
go = ["dep:phf", "dep:unicode-general-category"]
python = []

[dependencies]
windmill-queue.workspace = true
windmill-audit.workspace = true # there isn't really a reason for audit-worth actions to happen in the worker.
windmill-common = { workspace = true, features = [
    "tokio",
    "sqlx",
    "prometheus",
] }
windmill-api-client.workspace = true
sqlx.workspace = true
uuid.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
async-recursion.workspace = true
anyhow.workspace = true
itertools.workspace = true
regex.workspace = true
prometheus.workspace = true
lazy_static.workspace = true
chrono.workspace = true
dotenv.workspace = true
rand.workspace = true # TODO: Remove. only used by token creation hack.
deno_core = { workspace = true, optional = true }
swc_common = { workspace = true, optional = true }
swc_ecma_parser = { workspace = true, optional = true }
swc_ecma_ast = { workspace = true, optional = true }
phf = { workspace = true, optional = true }
unicode-general-category = { workspace = true, optional = true }
