[package]
name = "windmill-worker"
version.workspace = true
authors.workspace = true
edition.workspace = true
default-run = "worker"

[[bin]]
name = "worker"
path = "./src/main.rs"

[features]
default = ["deno", "go", "python"]
deno = ["dep:windmill-parser-ts", "dep:deno_core"]
go = ["dep:windmill-parser-go"]
python = ["dep:windmill-parser-py"]

[dependencies]
windmill-queue.workspace = true
windmill-audit.workspace = true # there isn't really a reason for audit-worth actions to happen in the worker.
windmill-common = { workspace = true, features = [
    "tokio",
    "sqlx",
    "prometheus",
    "tracing_init",
] }
windmill-api-client.workspace = true
windmill-parser.workspace = true
windmill-parser-ts = { workspace = true, optional = true }
windmill-parser-go = { workspace = true, optional = true }
windmill-parser-py = { workspace = true, optional = true }
sqlx.workspace = true
uuid.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
async-recursion.workspace = true
anyhow.workspace = true
itertools.workspace = true
regex.workspace = true
prometheus.workspace = true
lazy_static.workspace = true
chrono.workspace = true
dotenv.workspace = true
rand.workspace = true # TODO: Remove. only used by token creation hack.
deno_core = { workspace = true, optional = true }
