[package]
name = "windmill-worker"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
windmill-queue.workspace = true
windmill-common = { workspace = true, features = ["tokio", "sqlx"] }
windmill-api-client.workspace = true
sqlx.workspace = true
uuid.workspace = true
tracing.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
futures.workspace = true
async-recursion.workspace = true
anyhow.workspace = true
itertools.workspace = true
deno_core.workspace = true
regex.workspace = true
prometheus.workspace = true
lazy_static.workspace = true
chrono.workspace = true
