[package]
name = "openapi"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
url.workspace = true
uuid.workspace = true
reqwest = { workspace = true, features = ["json", "multipart"] }
