[package]
name = "windmill-api-client"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "windmill_api_client"
path = "./src/lib.rs"

[dependencies]
serde.workspace = true
serde_derive.workspace = true
serde_json.workspace = true
url.workspace = true
uuid.workspace = true
reqwest = { workspace = true, features = ["json", "multipart"] }
