[package]
name = "windmill-audit"
version = "0.1.0"
edition = "2021"

[lib]
name = "windmill_audit"
path = "./src/lib.rs"

[dependencies]
serde.workspace = true
sql-builder.workspace = true
sqlx.workspace = true
chrono.workspace = true
serde_json.workspace = true
tracing.workspace = true
windmill-common = { workspace = true, features = ["axum"] }
