[package]
name = "windmill-common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[features]
default = []
sqlx = ["dep:sqlx"]
hyper = ["dep:hyper"]
tokio = ["dep:tokio"]
axum = ["dep:axum", "dep:tracing"]
reqwest = ["dep:reqwest"]
prometheus = ["dep:prometheus"]
tracing_init = ["dep:tracing", "dep:tracing-subscriber"]
profiling = [
    "dep:pprof",
    "dep:tokio-stream",
    "dep:async-compression",
    "dep:tokio-util",
    "dep:bytes",
    "dep:querystring",
]

[lib]
name = "windmill_common"
path = "src/lib.rs"

[dependencies]
hmac.workspace = true
sha2.workspace = true
thiserror.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
hex.workspace = true
rand.workspace = true
sqlx = { workspace = true, optional = true, features = ["postgres"] }
uuid.workspace = true
prometheus = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
axum = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
pprof = { workspace = true, optional = true, features = ["protobuf-codec"] }
tokio-stream = { workspace = true, optional = true }
async-compression = { workspace = true, optional = true, features = ["gzip"] }
tokio-util = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
querystring = { workspace = true, optional = true }
