[package]
name = "windmill-queue"
version = "1.41.0"
authors = ["Ruben Fiszel <ruben@windmill.dev>"]
edition = "2021"

[lib]
name = "windmill_queue"
path = "src/lib.rs"

[dependencies]
windmill-audit.workspace = true
windmill-common = { workspace = true, features = ["sqlx", "reqwest"] }
anyhow.workspace = true
hmac.workspace = true
sql-builder.workspace = true
sqlx.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
ulid.workspace = true
uuid.workspace = true
chrono.workspace = true
hex.workspace = true
reqwest.workspace = true
lazy_static.workspace = true
prometheus.workspace = true
cron.workspace = true
