[package]
name = "windmill-parser"
version = "1.41.0"
authors = ["Ruben Fiszel <ruben@windmill.dev>"]
edition = "2021"

[lib]
name = "windmill_parser"
path = "./src/lib.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
