[package]
name = "windmill-parser"
version = "1.41.0"
edition.workspace = true
authors.workspace = true

[lib]
name = "windmill_parser"
path = "./src/lib.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
